#!/bin/sh
set -eu

stdout_path=
stderr_path=
while [ "$#" -gt 0 ]; do
  case "$1" in
    stdout) stdout_path=$2 ;;
    stderr) stderr_path=$2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift 2
done

test -n "$stdout_path"
test -n "$stderr_path"
mkdir -p "$(dirname "$stdout_path")" "$(dirname "$stderr_path")"
: >"$stdout_path"
: >"$stderr_path"
cat <&3 >>"$stdout_path" &
stdout_pid=$!
cat <&4 >>"$stderr_path" &
stderr_pid=$!
printf 1 >&5
wait "$stdout_pid" "$stderr_pid"
